### ISSUE TITLE
@:uiComp metadata behavior

### ISSUE THREAD

**Issue by rcstuber** [ncannasse/domkit#24]
The purpose of `@:uiComp` is unclear to me. The documentation states "`[...] add @:uiComp("name") metadata in order to customize the component name`", which suggests that the component can be given a different Tag name from its class name. However the macro uses that custom name to find the class of the component in the search paths, which now differs and cannot be found. How is this intended to be used/be useful?

Example:
```haxe
// BlinkingComp.hx
@:uiComp("blink")
class BlinkingComp extends h2d.Object implements h2d.domkit.Object {}

// Usage in some SRC
<blink/>
```
This won't work, as it will try to find `BlinkComp` class

**Comment by ncannasse** [comment]
If you do this you need to import BlinkComp in your SRC first.

**Comment by rcstuber** [comment]
Can you give an example please, as I don't understand how it will properly resolve the class if the tag name (`<blink>`) is different from the class name (`BlinkingComp`) from looking at the code here:

https://github.com/HeapsIO/domkit/blob/e8c6d319e523960818b8eb7d1c7932f552d28554/domkit/Macros.hx#L70

**Comment by ncannasse** [comment]
I think that if the Component has already been typed it will be in the
RESOLVED_COMPONENT Map, but that might be subject to type ordering.
We mainly use @:uiComp in order to rename "top level" components that are
not used in DomkitML

**Comment by rcstuber** [comment]
Thanks!

**Comment by tobil4sk** [comment]
> If you do this you need to import BlinkComp in your SRC first.

@ncannasse Could you clarify what you meant here? I also found this issue confusing and I would like to make a PR to make the documentation clearer.

**Comment by ncannasse** [comment]
Components are resolved using packages registered with `--init MyMacro.init()` that will call for example the following :

```haxe
domkit.Macros.registerComponentsPath("$");
domkit.Macros.registerComponentsPath("ui.comp.$");
```

Alternatively, instead of using automatic component resolution you can simply `import BlinkingComp` so it's part of the scope and accessible.

**Comment by tobil4sk** [comment]
Ah, yes, importing seems to make components in other packages accessible.

However, it still does not work if the component class is called `BlinkingComp` and the given component name is `blink` instead of `blinking`, like in the example from above:
```haxe
@:uiComp("blink")
class BlinkingComp extends h2d.Object implements h2d.domkit.Object {}
```
